// The 30 most frequent irregular verbs. Hand-maintained: unlike VerbCatalog.swift their forms
// cannot be derived, so every tense that cannot be built from other forms is spelled out.
// Condizionale (from the Futuro stem) and Passato prossimo (participle + auxiliary) are still derived.

enum IrregularVerbCatalog {
    static let seeds: [IrregularVerbSeed] = [
        IrregularVerbSeed(
            infinitive: "andare", ending: .are, meaning: "gehen, fahren", germanInfinitive: "gehen",
            presente: ["vado", "vai", "va", "andiamo", "andate", "vanno"],
            imperfetto: ["andavo", "andavi", "andava", "andavamo", "andavate", "andavano"],
            futuro: ["andrò", "andrai", "andrà", "andremo", "andrete", "andranno"],
            congiuntivo: ["vada", "vada", "vada", "andiamo", "andiate", "vadano"],
            imperativo: [nil, "va'", "vada", "andiamo", "andate", "vadano"],
            imperativoAlternatives: [1: ["vai", "va"]],
            participle: "andato", auxiliary: .essere,
            dePresente: ["gehe", "gehst", "geht", "gehen", "geht", "gehen"],
            dePraeteritum: ["ging", "gingst", "ging", "gingen", "gingt", "gingen"],
            deParticiple: "gegangen", deAuxiliary: .sein,
            deImperative: "geh"
        ),
        IrregularVerbSeed(
            infinitive: "aprire", ending: .ire, meaning: "öffnen", germanInfinitive: "öffnen",
            presente: ["apro", "apri", "apre", "apriamo", "aprite", "aprono"],
            imperfetto: ["aprivo", "aprivi", "apriva", "aprivamo", "aprivate", "aprivano"],
            futuro: ["aprirò", "aprirai", "aprirà", "apriremo", "aprirete", "apriranno"],
            congiuntivo: ["apra", "apra", "apra", "apriamo", "apriate", "aprano"],
            imperativo: [nil, "apri", "apra", "apriamo", "aprite", "aprano"],
            participle: "aperto", auxiliary: .avere,
            dePresente: ["öffne", "öffnest", "öffnet", "öffnen", "öffnet", "öffnen"],
            dePraeteritum: ["öffnete", "öffnetest", "öffnete", "öffneten", "öffnetet", "öffneten"],
            deParticiple: "geöffnet", deAuxiliary: .haben,
            deImperative: "öffne"
        ),
        IrregularVerbSeed(
            infinitive: "avere", ending: .ere, meaning: "haben", germanInfinitive: "haben",
            presente: ["ho", "hai", "ha", "abbiamo", "avete", "hanno"],
            imperfetto: ["avevo", "avevi", "aveva", "avevamo", "avevate", "avevano"],
            futuro: ["avrò", "avrai", "avrà", "avremo", "avrete", "avranno"],
            congiuntivo: ["abbia", "abbia", "abbia", "abbiamo", "abbiate", "abbiano"],
            imperativo: [nil, "abbi", "abbia", "abbiamo", "abbiate", "abbiano"],
            participle: "avuto", auxiliary: .avere,
            dePresente: ["habe", "hast", "hat", "haben", "habt", "haben"],
            dePraeteritum: ["hatte", "hattest", "hatte", "hatten", "hattet", "hatten"],
            deParticiple: "gehabt", deAuxiliary: .haben,
            deImperative: "hab"
        ),
        IrregularVerbSeed(
            infinitive: "bere", ending: .ere, meaning: "trinken", germanInfinitive: "trinken",
            presente: ["bevo", "bevi", "beve", "beviamo", "bevete", "bevono"],
            imperfetto: ["bevevo", "bevevi", "beveva", "bevevamo", "bevevate", "bevevano"],
            futuro: ["berrò", "berrai", "berrà", "berremo", "berrete", "berranno"],
            congiuntivo: ["beva", "beva", "beva", "beviamo", "beviate", "bevano"],
            imperativo: [nil, "bevi", "beva", "beviamo", "bevete", "bevano"],
            participle: "bevuto", auxiliary: .avere,
            dePresente: ["trinke", "trinkst", "trinkt", "trinken", "trinkt", "trinken"],
            dePraeteritum: ["trank", "trankst", "trank", "tranken", "trankt", "tranken"],
            deParticiple: "getrunken", deAuxiliary: .haben,
            deImperative: "trink"
        ),
        IrregularVerbSeed(
            infinitive: "cadere", ending: .ere, meaning: "fallen", germanInfinitive: "fallen",
            presente: ["cado", "cadi", "cade", "cadiamo", "cadete", "cadono"],
            imperfetto: ["cadevo", "cadevi", "cadeva", "cadevamo", "cadevate", "cadevano"],
            futuro: ["cadrò", "cadrai", "cadrà", "cadremo", "cadrete", "cadranno"],
            congiuntivo: ["cada", "cada", "cada", "cadiamo", "cadiate", "cadano"],
            imperativo: [nil, "cadi", "cada", "cadiamo", "cadete", "cadano"],
            participle: "caduto", auxiliary: .essere,
            dePresente: ["falle", "fällst", "fällt", "fallen", "fallt", "fallen"],
            dePraeteritum: ["fiel", "fielst", "fiel", "fielen", "fielt", "fielen"],
            deParticiple: "gefallen", deAuxiliary: .sein,
            deImperative: "fall"
        ),
        IrregularVerbSeed(
            infinitive: "chiedere", ending: .ere, meaning: "fragen, bitten", germanInfinitive: "fragen",
            presente: ["chiedo", "chiedi", "chiede", "chiediamo", "chiedete", "chiedono"],
            imperfetto: ["chiedevo", "chiedevi", "chiedeva", "chiedevamo", "chiedevate", "chiedevano"],
            futuro: ["chiederò", "chiederai", "chiederà", "chiederemo", "chiederete", "chiederanno"],
            congiuntivo: ["chieda", "chieda", "chieda", "chiediamo", "chiediate", "chiedano"],
            imperativo: [nil, "chiedi", "chieda", "chiediamo", "chiedete", "chiedano"],
            participle: "chiesto", auxiliary: .avere,
            dePresente: ["frage", "fragst", "fragt", "fragen", "fragt", "fragen"],
            dePraeteritum: ["fragte", "fragtest", "fragte", "fragten", "fragtet", "fragten"],
            deParticiple: "gefragt", deAuxiliary: .haben,
            deImperative: "frag"
        ),
        IrregularVerbSeed(
            infinitive: "conoscere", ending: .ere, meaning: "kennen, kennenlernen", germanInfinitive: "kennen",
            presente: ["conosco", "conosci", "conosce", "conosciamo", "conoscete", "conoscono"],
            imperfetto: ["conoscevo", "conoscevi", "conosceva", "conoscevamo", "conoscevate", "conoscevano"],
            futuro: ["conoscerò", "conoscerai", "conoscerà", "conosceremo", "conoscerete", "conosceranno"],
            congiuntivo: ["conosca", "conosca", "conosca", "conosciamo", "conosciate", "conoscano"],
            imperativo: [nil, "conosci", "conosca", "conosciamo", "conoscete", "conoscano"],
            participle: "conosciuto", auxiliary: .avere,
            dePresente: ["kenne", "kennst", "kennt", "kennen", "kennt", "kennen"],
            dePraeteritum: ["kannte", "kanntest", "kannte", "kannten", "kanntet", "kannten"],
            deParticiple: "gekannt", deAuxiliary: .haben,
            deImperative: "kenn"
        ),
        IrregularVerbSeed(
            infinitive: "dare", ending: .are, meaning: "geben", germanInfinitive: "geben",
            presente: ["do", "dai", "dà", "diamo", "date", "danno"],
            imperfetto: ["davo", "davi", "dava", "davamo", "davate", "davano"],
            futuro: ["darò", "darai", "darà", "daremo", "darete", "daranno"],
            congiuntivo: ["dia", "dia", "dia", "diamo", "diate", "diano"],
            imperativo: [nil, "da'", "dia", "diamo", "date", "diano"],
            imperativoAlternatives: [1: ["dai", "da"]],
            participle: "dato", auxiliary: .avere,
            dePresente: ["gebe", "gibst", "gibt", "geben", "gebt", "geben"],
            dePraeteritum: ["gab", "gabst", "gab", "gaben", "gabt", "gaben"],
            deParticiple: "gegeben", deAuxiliary: .haben,
            deImperative: "gib"
        ),
        IrregularVerbSeed(
            infinitive: "decidere", ending: .ere, meaning: "entscheiden", germanInfinitive: "entscheiden",
            presente: ["decido", "decidi", "decide", "decidiamo", "decidete", "decidono"],
            imperfetto: ["decidevo", "decidevi", "decideva", "decidevamo", "decidevate", "decidevano"],
            futuro: ["deciderò", "deciderai", "deciderà", "decideremo", "deciderete", "decideranno"],
            congiuntivo: ["decida", "decida", "decida", "decidiamo", "decidiate", "decidano"],
            imperativo: [nil, "decidi", "decida", "decidiamo", "decidete", "decidano"],
            participle: "deciso", auxiliary: .avere,
            dePresente: ["entscheide", "entscheidest", "entscheidet", "entscheiden", "entscheidet", "entscheiden"],
            dePraeteritum: ["entschied", "entschiedest", "entschied", "entschieden", "entschiedet", "entschieden"],
            deParticiple: "entschieden", deAuxiliary: .haben,
            deImperative: "entscheide"
        ),
        IrregularVerbSeed(
            infinitive: "dire", ending: .ire, meaning: "sagen", germanInfinitive: "sagen",
            presente: ["dico", "dici", "dice", "diciamo", "dite", "dicono"],
            imperfetto: ["dicevo", "dicevi", "diceva", "dicevamo", "dicevate", "dicevano"],
            futuro: ["dirò", "dirai", "dirà", "diremo", "direte", "diranno"],
            congiuntivo: ["dica", "dica", "dica", "diciamo", "diciate", "dicano"],
            imperativo: [nil, "di'", "dica", "diciamo", "dite", "dicano"],
            participle: "detto", auxiliary: .avere,
            dePresente: ["sage", "sagst", "sagt", "sagen", "sagt", "sagen"],
            dePraeteritum: ["sagte", "sagtest", "sagte", "sagten", "sagtet", "sagten"],
            deParticiple: "gesagt", deAuxiliary: .haben,
            deImperative: "sag"
        ),
        IrregularVerbSeed(
            infinitive: "dovere", ending: .ere, meaning: "müssen, sollen", germanInfinitive: "müssen",
            presente: ["devo", "devi", "deve", "dobbiamo", "dovete", "devono"],
            imperfetto: ["dovevo", "dovevi", "doveva", "dovevamo", "dovevate", "dovevano"],
            futuro: ["dovrò", "dovrai", "dovrà", "dovremo", "dovrete", "dovranno"],
            congiuntivo: ["debba", "debba", "debba", "dobbiamo", "dobbiate", "debbano"],
            imperativo: nil,
            participle: "dovuto", auxiliary: .avere,
            dePresente: ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
            dePraeteritum: ["musste", "musstest", "musste", "mussten", "musstet", "mussten"],
            deParticiple: "gemusst", deAuxiliary: .haben,
            deImperative: ""
        ),
        IrregularVerbSeed(
            infinitive: "essere", ending: .ere, meaning: "sein", germanInfinitive: "sein",
            presente: ["sono", "sei", "è", "siamo", "siete", "sono"],
            imperfetto: ["ero", "eri", "era", "eravamo", "eravate", "erano"],
            futuro: ["sarò", "sarai", "sarà", "saremo", "sarete", "saranno"],
            congiuntivo: ["sia", "sia", "sia", "siamo", "siate", "siano"],
            imperativo: [nil, "sii", "sia", "siamo", "siate", "siano"],
            participle: "stato", auxiliary: .essere,
            dePresente: ["bin", "bist", "ist", "sind", "seid", "sind"],
            dePraeteritum: ["war", "warst", "war", "waren", "wart", "waren"],
            deParticiple: "gewesen", deAuxiliary: .sein,
            deImperativo: [nil, "sei", "seien sie", "seien wir", "seid", "seien sie"]
        ),
        IrregularVerbSeed(
            infinitive: "fare", ending: .are, meaning: "machen, tun", germanInfinitive: "machen",
            presente: ["faccio", "fai", "fa", "facciamo", "fate", "fanno"],
            imperfetto: ["facevo", "facevi", "faceva", "facevamo", "facevate", "facevano"],
            futuro: ["farò", "farai", "farà", "faremo", "farete", "faranno"],
            congiuntivo: ["faccia", "faccia", "faccia", "facciamo", "facciate", "facciano"],
            imperativo: [nil, "fa'", "faccia", "facciamo", "fate", "facciano"],
            imperativoAlternatives: [1: ["fai", "fa"]],
            participle: "fatto", auxiliary: .avere,
            dePresente: ["mache", "machst", "macht", "machen", "macht", "machen"],
            dePraeteritum: ["machte", "machtest", "machte", "machten", "machtet", "machten"],
            deParticiple: "gemacht", deAuxiliary: .haben,
            deImperative: "mach"
        ),
        IrregularVerbSeed(
            infinitive: "leggere", ending: .ere, meaning: "lesen", germanInfinitive: "lesen",
            presente: ["leggo", "leggi", "legge", "leggiamo", "leggete", "leggono"],
            imperfetto: ["leggevo", "leggevi", "leggeva", "leggevamo", "leggevate", "leggevano"],
            futuro: ["leggerò", "leggerai", "leggerà", "leggeremo", "leggerete", "leggeranno"],
            congiuntivo: ["legga", "legga", "legga", "leggiamo", "leggiate", "leggano"],
            imperativo: [nil, "leggi", "legga", "leggiamo", "leggete", "leggano"],
            participle: "letto", auxiliary: .avere,
            dePresente: ["lese", "liest", "liest", "lesen", "lest", "lesen"],
            dePraeteritum: ["las", "last", "las", "lasen", "last", "lasen"],
            deParticiple: "gelesen", deAuxiliary: .haben,
            deImperative: "lies"
        ),
        IrregularVerbSeed(
            infinitive: "mettere", ending: .ere, meaning: "legen, stellen, setzen", germanInfinitive: "legen",
            presente: ["metto", "metti", "mette", "mettiamo", "mettete", "mettono"],
            imperfetto: ["mettevo", "mettevi", "metteva", "mettevamo", "mettevate", "mettevano"],
            futuro: ["metterò", "metterai", "metterà", "metteremo", "metterete", "metteranno"],
            congiuntivo: ["metta", "metta", "metta", "mettiamo", "mettiate", "mettano"],
            imperativo: [nil, "metti", "metta", "mettiamo", "mettete", "mettano"],
            participle: "messo", auxiliary: .avere,
            dePresente: ["lege", "legst", "legt", "legen", "legt", "legen"],
            dePraeteritum: ["legte", "legtest", "legte", "legten", "legtet", "legten"],
            deParticiple: "gelegt", deAuxiliary: .haben,
            deImperative: "leg"
        ),
        IrregularVerbSeed(
            infinitive: "piacere", ending: .ere, meaning: "gefallen, mögen", germanInfinitive: "gefallen",
            presente: ["piaccio", "piaci", "piace", "piacciamo", "piacete", "piacciono"],
            imperfetto: ["piacevo", "piacevi", "piaceva", "piacevamo", "piacevate", "piacevano"],
            futuro: ["piacerò", "piacerai", "piacerà", "piaceremo", "piacerete", "piaceranno"],
            congiuntivo: ["piaccia", "piaccia", "piaccia", "piacciamo", "piacciate", "piacciano"],
            imperativo: nil,
            participle: "piaciuto", auxiliary: .essere,
            dePresente: ["gefalle", "gefällst", "gefällt", "gefallen", "gefallt", "gefallen"],
            dePraeteritum: ["gefiel", "gefielst", "gefiel", "gefielen", "gefielt", "gefielen"],
            deParticiple: "gefallen", deAuxiliary: .haben,
            deImperative: ""
        ),
        IrregularVerbSeed(
            infinitive: "potere", ending: .ere, meaning: "können", germanInfinitive: "können",
            presente: ["posso", "puoi", "può", "possiamo", "potete", "possono"],
            imperfetto: ["potevo", "potevi", "poteva", "potevamo", "potevate", "potevano"],
            futuro: ["potrò", "potrai", "potrà", "potremo", "potrete", "potranno"],
            congiuntivo: ["possa", "possa", "possa", "possiamo", "possiate", "possano"],
            imperativo: nil,
            participle: "potuto", auxiliary: .avere,
            dePresente: ["kann", "kannst", "kann", "können", "könnt", "können"],
            dePraeteritum: ["konnte", "konntest", "konnte", "konnten", "konntet", "konnten"],
            deParticiple: "gekonnt", deAuxiliary: .haben,
            deImperative: ""
        ),
        IrregularVerbSeed(
            infinitive: "prendere", ending: .ere, meaning: "nehmen", germanInfinitive: "nehmen",
            presente: ["prendo", "prendi", "prende", "prendiamo", "prendete", "prendono"],
            imperfetto: ["prendevo", "prendevi", "prendeva", "prendevamo", "prendevate", "prendevano"],
            futuro: ["prenderò", "prenderai", "prenderà", "prenderemo", "prenderete", "prenderanno"],
            congiuntivo: ["prenda", "prenda", "prenda", "prendiamo", "prendiate", "prendano"],
            imperativo: [nil, "prendi", "prenda", "prendiamo", "prendete", "prendano"],
            participle: "preso", auxiliary: .avere,
            dePresente: ["nehme", "nimmst", "nimmt", "nehmen", "nehmt", "nehmen"],
            dePraeteritum: ["nahm", "nahmst", "nahm", "nahmen", "nahmt", "nahmen"],
            deParticiple: "genommen", deAuxiliary: .haben,
            deImperative: "nimm"
        ),
        IrregularVerbSeed(
            infinitive: "rimanere", ending: .ere, meaning: "bleiben", germanInfinitive: "bleiben",
            presente: ["rimango", "rimani", "rimane", "rimaniamo", "rimanete", "rimangono"],
            imperfetto: ["rimanevo", "rimanevi", "rimaneva", "rimanevamo", "rimanevate", "rimanevano"],
            futuro: ["rimarrò", "rimarrai", "rimarrà", "rimarremo", "rimarrete", "rimarranno"],
            congiuntivo: ["rimanga", "rimanga", "rimanga", "rimaniamo", "rimaniate", "rimangano"],
            imperativo: [nil, "rimani", "rimanga", "rimaniamo", "rimanete", "rimangano"],
            participle: "rimasto", auxiliary: .essere,
            dePresente: ["bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"],
            dePraeteritum: ["blieb", "bliebst", "blieb", "blieben", "bliebt", "blieben"],
            deParticiple: "geblieben", deAuxiliary: .sein,
            deImperative: "bleib"
        ),
        IrregularVerbSeed(
            infinitive: "rispondere", ending: .ere, meaning: "antworten", germanInfinitive: "antworten",
            presente: ["rispondo", "rispondi", "risponde", "rispondiamo", "rispondete", "rispondono"],
            imperfetto: ["rispondevo", "rispondevi", "rispondeva", "rispondevamo", "rispondevate", "rispondevano"],
            futuro: ["risponderò", "risponderai", "risponderà", "risponderemo", "risponderete", "risponderanno"],
            congiuntivo: ["risponda", "risponda", "risponda", "rispondiamo", "rispondiate", "rispondano"],
            imperativo: [nil, "rispondi", "risponda", "rispondiamo", "rispondete", "rispondano"],
            participle: "risposto", auxiliary: .avere,
            dePresente: ["antworte", "antwortest", "antwortet", "antworten", "antwortet", "antworten"],
            dePraeteritum: ["antwortete", "antwortetest", "antwortete", "antworteten", "antwortetet", "antworteten"],
            deParticiple: "geantwortet", deAuxiliary: .haben,
            deImperative: "antworte"
        ),
        IrregularVerbSeed(
            infinitive: "sapere", ending: .ere, meaning: "wissen, können", germanInfinitive: "wissen",
            presente: ["so", "sai", "sa", "sappiamo", "sapete", "sanno"],
            imperfetto: ["sapevo", "sapevi", "sapeva", "sapevamo", "sapevate", "sapevano"],
            futuro: ["saprò", "saprai", "saprà", "sapremo", "saprete", "sapranno"],
            congiuntivo: ["sappia", "sappia", "sappia", "sappiamo", "sappiate", "sappiano"],
            imperativo: [nil, "sappi", "sappia", "sappiamo", "sappiate", "sappiano"],
            participle: "saputo", auxiliary: .avere,
            dePresente: ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
            dePraeteritum: ["wusste", "wusstest", "wusste", "wussten", "wusstet", "wussten"],
            deParticiple: "gewusst", deAuxiliary: .haben,
            deImperative: "wisse"
        ),
        IrregularVerbSeed(
            infinitive: "scegliere", ending: .ere, meaning: "wählen, auswählen", germanInfinitive: "wählen",
            presente: ["scelgo", "scegli", "sceglie", "scegliamo", "scegliete", "scelgono"],
            imperfetto: ["sceglievo", "sceglievi", "sceglieva", "sceglievamo", "sceglievate", "sceglievano"],
            futuro: ["sceglierò", "sceglierai", "sceglierà", "sceglieremo", "sceglierete", "sceglieranno"],
            congiuntivo: ["scelga", "scelga", "scelga", "scegliamo", "scegliate", "scelgano"],
            imperativo: [nil, "scegli", "scelga", "scegliamo", "scegliete", "scelgano"],
            participle: "scelto", auxiliary: .avere,
            dePresente: ["wähle", "wählst", "wählt", "wählen", "wählt", "wählen"],
            dePraeteritum: ["wählte", "wähltest", "wählte", "wählten", "wähltet", "wählten"],
            deParticiple: "gewählt", deAuxiliary: .haben,
            deImperative: "wähl"
        ),
        IrregularVerbSeed(
            infinitive: "scrivere", ending: .ere, meaning: "schreiben", germanInfinitive: "schreiben",
            presente: ["scrivo", "scrivi", "scrive", "scriviamo", "scrivete", "scrivono"],
            imperfetto: ["scrivevo", "scrivevi", "scriveva", "scrivevamo", "scrivevate", "scrivevano"],
            futuro: ["scriverò", "scriverai", "scriverà", "scriveremo", "scriverete", "scriveranno"],
            congiuntivo: ["scriva", "scriva", "scriva", "scriviamo", "scriviate", "scrivano"],
            imperativo: [nil, "scrivi", "scriva", "scriviamo", "scrivete", "scrivano"],
            participle: "scritto", auxiliary: .avere,
            dePresente: ["schreibe", "schreibst", "schreibt", "schreiben", "schreibt", "schreiben"],
            dePraeteritum: ["schrieb", "schriebst", "schrieb", "schrieben", "schriebt", "schrieben"],
            deParticiple: "geschrieben", deAuxiliary: .haben,
            deImperative: "schreib"
        ),
        IrregularVerbSeed(
            infinitive: "stare", ending: .are, meaning: "sich befinden, bleiben", germanInfinitive: "sich befinden",
            presente: ["sto", "stai", "sta", "stiamo", "state", "stanno"],
            imperfetto: ["stavo", "stavi", "stava", "stavamo", "stavate", "stavano"],
            futuro: ["starò", "starai", "starà", "staremo", "starete", "staranno"],
            congiuntivo: ["stia", "stia", "stia", "stiamo", "stiate", "stiano"],
            imperativo: [nil, "sta'", "stia", "stiamo", "state", "stiano"],
            imperativoAlternatives: [1: ["stai", "sta"]],
            participle: "stato", auxiliary: .essere,
            dePresente: ["befinde mich", "befindest dich", "befindet sich", "befinden uns", "befindet euch", "befinden sich"],
            dePraeteritum: ["befand mich", "befandest dich", "befand sich", "befanden uns", "befandet euch", "befanden sich"],
            deParticiple: "befunden", deAuxiliary: .haben,
            deImperativo: [nil, "befinde dich", "befinden sie sich", "befinden wir uns", "befindet euch", "befinden sie sich"]
        ),
        IrregularVerbSeed(
            infinitive: "tenere", ending: .ere, meaning: "halten", germanInfinitive: "halten",
            presente: ["tengo", "tieni", "tiene", "teniamo", "tenete", "tengono"],
            imperfetto: ["tenevo", "tenevi", "teneva", "tenevamo", "tenevate", "tenevano"],
            futuro: ["terrò", "terrai", "terrà", "terremo", "terrete", "terranno"],
            congiuntivo: ["tenga", "tenga", "tenga", "teniamo", "teniate", "tengano"],
            imperativo: [nil, "tieni", "tenga", "teniamo", "tenete", "tengano"],
            participle: "tenuto", auxiliary: .avere,
            dePresente: ["halte", "hältst", "hält", "halten", "haltet", "halten"],
            dePraeteritum: ["hielt", "hieltst", "hielt", "hielten", "hieltet", "hielten"],
            deParticiple: "gehalten", deAuxiliary: .haben,
            deImperative: "halt"
        ),
        IrregularVerbSeed(
            infinitive: "uscire", ending: .ire, meaning: "hinausgehen, ausgehen", germanInfinitive: "ausgehen",
            presente: ["esco", "esci", "esce", "usciamo", "uscite", "escono"],
            imperfetto: ["uscivo", "uscivi", "usciva", "uscivamo", "uscivate", "uscivano"],
            futuro: ["uscirò", "uscirai", "uscirà", "usciremo", "uscirete", "usciranno"],
            congiuntivo: ["esca", "esca", "esca", "usciamo", "usciate", "escano"],
            imperativo: [nil, "esci", "esca", "usciamo", "uscite", "escano"],
            participle: "uscito", auxiliary: .essere,
            dePresente: ["gehe aus", "gehst aus", "geht aus", "gehen aus", "geht aus", "gehen aus"],
            dePraeteritum: ["ging aus", "gingst aus", "ging aus", "gingen aus", "gingt aus", "gingen aus"],
            deParticiple: "ausgegangen", deAuxiliary: .sein,
            deImperativo: [nil, "geh aus", "gehen sie aus", "gehen wir aus", "geht aus", "gehen sie aus"]
        ),
        IrregularVerbSeed(
            infinitive: "vedere", ending: .ere, meaning: "sehen", germanInfinitive: "sehen",
            presente: ["vedo", "vedi", "vede", "vediamo", "vedete", "vedono"],
            imperfetto: ["vedevo", "vedevi", "vedeva", "vedevamo", "vedevate", "vedevano"],
            futuro: ["vedrò", "vedrai", "vedrà", "vedremo", "vedrete", "vedranno"],
            congiuntivo: ["veda", "veda", "veda", "vediamo", "vediate", "vedano"],
            imperativo: [nil, "vedi", "veda", "vediamo", "vedete", "vedano"],
            participle: "visto", auxiliary: .avere,
            dePresente: ["sehe", "siehst", "sieht", "sehen", "seht", "sehen"],
            dePraeteritum: ["sah", "sahst", "sah", "sahen", "saht", "sahen"],
            deParticiple: "gesehen", deAuxiliary: .haben,
            deImperative: "sieh"
        ),
        IrregularVerbSeed(
            infinitive: "venire", ending: .ire, meaning: "kommen", germanInfinitive: "kommen",
            presente: ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"],
            imperfetto: ["venivo", "venivi", "veniva", "venivamo", "venivate", "venivano"],
            futuro: ["verrò", "verrai", "verrà", "verremo", "verrete", "verranno"],
            congiuntivo: ["venga", "venga", "venga", "veniamo", "veniate", "vengano"],
            imperativo: [nil, "vieni", "venga", "veniamo", "venite", "vengano"],
            participle: "venuto", auxiliary: .essere,
            dePresente: ["komme", "kommst", "kommt", "kommen", "kommt", "kommen"],
            dePraeteritum: ["kam", "kamst", "kam", "kamen", "kamt", "kamen"],
            deParticiple: "gekommen", deAuxiliary: .sein,
            deImperative: "komm"
        ),
        IrregularVerbSeed(
            infinitive: "vivere", ending: .ere, meaning: "leben", germanInfinitive: "leben",
            presente: ["vivo", "vivi", "vive", "viviamo", "vivete", "vivono"],
            imperfetto: ["vivevo", "vivevi", "viveva", "vivevamo", "vivevate", "vivevano"],
            futuro: ["vivrò", "vivrai", "vivrà", "vivremo", "vivrete", "vivranno"],
            congiuntivo: ["viva", "viva", "viva", "viviamo", "viviate", "vivano"],
            imperativo: [nil, "vivi", "viva", "viviamo", "vivete", "vivano"],
            participle: "vissuto", auxiliary: .avere,
            dePresente: ["lebe", "lebst", "lebt", "leben", "lebt", "leben"],
            dePraeteritum: ["lebte", "lebtest", "lebte", "lebten", "lebtet", "lebten"],
            deParticiple: "gelebt", deAuxiliary: .haben,
            deImperative: "leb"
        ),
        IrregularVerbSeed(
            infinitive: "volere", ending: .ere, meaning: "wollen", germanInfinitive: "wollen",
            presente: ["voglio", "vuoi", "vuole", "vogliamo", "volete", "vogliono"],
            imperfetto: ["volevo", "volevi", "voleva", "volevamo", "volevate", "volevano"],
            futuro: ["vorrò", "vorrai", "vorrà", "vorremo", "vorrete", "vorranno"],
            congiuntivo: ["voglia", "voglia", "voglia", "vogliamo", "vogliate", "vogliano"],
            imperativo: nil,
            participle: "voluto", auxiliary: .avere,
            dePresente: ["will", "willst", "will", "wollen", "wollt", "wollen"],
            dePraeteritum: ["wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"],
            deParticiple: "gewollt", deAuxiliary: .haben,
            deImperative: ""
        ),
    ]
}
