// Generated by tools/generate-swift-data.py from prototype/index.html.
// Edit the prototype and re-run the script rather than editing by hand.

extension TenseInfo {
    static let all: [Tense: TenseInfo] = [
        .presente: TenseInfo(
            translation: "entspricht dem deutschen Präsens: „ich spreche“, „ich glaube“",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "Grundregel:", text: "Die Endung des Infinitivs (-are, -ere, -ire) fällt weg, an den Stamm treten personenbezogene Endungen."),
                    .init(label: "Sonderfall -isc-:", text: "Eine Gruppe von -ire-Verben (z. B. capire) schiebt vor den Endungen der Singularformen und der 3. Pl. zusätzlich -isc- ein."),
                    .init(label: "Merken:", text: "Welche -ire-Verben das tun, folgt keiner Regel — das ist reiner Auswendiglern-Stoff."),
                ])),
                .init(heading: "Endungen", content: .table(columns: ["-are", "-ere", "-ire", "-ire (isc)"], rows: [
                    ["io", "-o", "-o", "-o", "-isco"],
                    ["tu", "-i", "-i", "-i", "-isci"],
                    ["lui/lei", "-a", "-e", "-e", "-isce"],
                    ["noi", "-iamo", "-iamo", "-iamo", "-iamo"],
                    ["voi", "-ate", "-ete", "-ite", "-ite"],
                    ["loro", "-ano", "-ono", "-ono", "-iscono"],
                ])),
                .init(heading: "Verwendung", content: .paragraph("Wie im Deutschen für aktuelle Handlungen, allgemeine Wahrheiten und Gewohnheiten. Anders als im Deutschen steht es im Italienischen oft auch für nahe Zukunft: „Domani parlo con lui“ = „Morgen spreche ich mit ihm.“")),
            ]
        ),
        .passatoprossimo: TenseInfo(
            translation: "entspricht dem deutschen Perfekt: „ich habe gesprochen“, „ich bin abgereist“",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "Aufbau:", text: "Hilfsverb im Presente (avere oder essere) + Partizip Perfekt."),
                    .init(label: "Partizip:", text: "Fast immer regelmäßig: -are → -ato, -ere → -uto, -ire → -ito (parlato, creduto, dormito, capito)."),
                    .init(label: "Hilfsverb avere:", text: "Der Normalfall — fast alle Verben hier nutzen avere."),
                    .init(label: "Hilfsverb essere:", text: "Nur Verben der Bewegung/Zustandsänderung wie partire. Dort passt sich das Partizip an das Subjekt an (partito/partita/partiti/partite) — hier vereinfacht immer männlich gezeigt."),
                ])),
                .init(heading: "Hilfsverb im Presente", content: .table(columns: ["avere", "essere"], rows: [
                    ["io", "ho", "sono"],
                    ["tu", "hai", "sei"],
                    ["lui/lei", "ha", "è"],
                    ["noi", "abbiamo", "siamo"],
                    ["voi", "avete", "siete"],
                    ["loro", "hanno", "sono"],
                ])),
                .init(heading: "Verwendung", content: .list([
                    .init(label: "Grundfrage:", text: "Beantwortet „Was ist passiert?“ — ein einzelnes, abgeschlossenes Ereignis."),
                    .init(label: "Abgeschlossene Handlung:", text: "„Ho visto Marco in città.“ = „Ich habe Marco in der Stadt gesehen.“"),
                    .init(label: "Handlungsketten:", text: "„Prima sono andata a fare la spesa, poi ho cucinato.“ = „Zuerst bin ich einkaufen gegangen, dann habe ich gekocht.“"),
                    .init(label: "Signalwörter:", text: "tutto il giorno, all'improvviso, appena, da … a"),
                ])),
                .init(heading: "Passato prossimo vs. Imperfetto", content: .list([
                    .init(label: "Im selben Satz:", text: "„Quando ho visto Maria, splendeva il sole.“ = „Als ich Maria sah, schien die Sonne.“ — die abgeschlossene Handlung steht im passato prossimo, der Hintergrund dazu im imperfetto."),
                    .init(label: "Bedeutung kann kippen:", text: "„Ho conosciuto“ = ich habe kennengelernt, aber „conoscevo“ = ich kannte; „ho avuto paura“ = ich bekam Angst, aber „avevo paura“ = ich hatte Angst."),
                ])),
            ]
        ),
        .imperfetto: TenseInfo(
            translation: "entspricht dem deutschen Präteritum bei Beschreibungen/Gewohnheiten: „ich sprach“, „ich sprach gerade“",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "Stamm:", text: "Die Infinitiv-Endung -re fällt komplett weg (parlare → parla-, credere → crede-, dormire → dormi-), der Themavokal (a/e/i) bleibt also erhalten."),
                    .init(label: "Endungen:", text: "Für alle drei Gruppen identisch — der einzige Unterschied ist der Stammvokal (a / e / i)."),
                    .init(label: "Keine Ausnahme bei -isc-:", text: "capire bildet das Imperfetto ganz normal (capivo, nicht capiscevo)."),
                ])),
                .init(heading: "Endungen (alle Gruppen gleich)", content: .table(columns: ["Endung"], rows: [
                    ["io", "-vo"],
                    ["tu", "-vi"],
                    ["lui/lei", "-va"],
                    ["noi", "-vamo"],
                    ["voi", "-vate"],
                    ["loro", "-vano"],
                ])),
                .init(heading: "Verwendung", content: .list([
                    .init(label: "Grundfrage:", text: "Beantwortet „Wie war die Situation?“ / „Wie war es normalerweise?“."),
                    .init(label: "Hintergrund:", text: "„Faceva molto freddo.“ = „Es war sehr kalt.“"),
                    .init(label: "Gewohnheit:", text: "„Da bambino giocavo sempre con il mio cane.“ = „Als Kind habe ich immer mit meinem Hund gespielt.“"),
                    .init(label: "Signalwörter:", text: "sempre, normalmente, mentre"),
                ])),
                .init(heading: "Passato prossimo vs. Imperfetto", content: .list([
                    .init(label: "Im selben Satz:", text: "„Quando ho visto Maria, splendeva il sole.“ = „Als ich Maria sah, schien die Sonne.“ — die abgeschlossene Handlung steht im passato prossimo, der Hintergrund dazu im imperfetto."),
                    .init(label: "Bedeutung kann kippen:", text: "„Ho conosciuto“ = ich habe kennengelernt, aber „conoscevo“ = ich kannte; „ho avuto paura“ = ich bekam Angst, aber „avevo paura“ = ich hatte Angst."),
                ])),
            ]
        ),
        .futuro: TenseInfo(
            translation: "entspricht dem deutschen Futur I: „ich werde sprechen“",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "-are-Verben:", text: "Das -a- der Endung wird zu -e- (parlare → parler-)."),
                    .init(label: "-ere-/-ire-Verben:", text: "Nur das finale -e des Infinitivs fällt weg (credere → creder-, dormire → dormir-)."),
                    .init(label: "Endungen:", text: "Für alle Gruppen identisch. Auch capire verhält sich regelmäßig (capirò)."),
                ])),
                .init(heading: "Endungen (alle Gruppen gleich)", content: .table(columns: ["Endung"], rows: [
                    ["io", "-ò"],
                    ["tu", "-ai"],
                    ["lui/lei", "-à"],
                    ["noi", "-emo"],
                    ["voi", "-ete"],
                    ["loro", "-anno"],
                ])),
                .init(heading: "Verwendung", content: .paragraph("Für zukünftige Handlungen, ähnlich dem deutschen Futur I. Im Alltagsitalienisch wird für die nahe Zukunft aber oft auch einfach das Presente verwendet.")),
            ]
        ),
        .condizionale: TenseInfo(
            translation: "entspricht dem deutschen Konjunktiv II mit würde: „ich würde sprechen“",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "Stamm:", text: "Derselbe wie beim Futuro semplice (z. B. parler-, creder-, dormir-)."),
                    .init(label: "Endungen:", text: "Eigene Endungen, für alle drei Verbgruppen identisch."),
                ])),
                .init(heading: "Endungen (alle Gruppen gleich)", content: .table(columns: ["Endung"], rows: [
                    ["io", "-ei"],
                    ["tu", "-esti"],
                    ["lui/lei", "-ebbe"],
                    ["noi", "-emmo"],
                    ["voi", "-este"],
                    ["loro", "-ebbero"],
                ])),
                .init(heading: "Verwendung", content: .paragraph("Für höfliche Bitten, Wünsche und hypothetische Aussagen — wie das deutsche „würde“ + Infinitiv oder Konjunktiv II: „Vorrei un caffè“ = „Ich hätte gern einen Kaffee“, „Parlerei con lui“ = „Ich würde mit ihm sprechen“.")),
            ]
        ),
        .congiuntivo: TenseInfo(
            translation: "hat keine direkte deutsche Entsprechung — im dass-Satz steht im Deutschen meist ganz normal der Indikativ",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "Auslöser:", text: "Steht fast immer nach che in einem Nebensatz, ausgelöst durch Verben/Ausdrücke des Wunsches, Zweifels, der Meinung oder Emotion im Hauptsatz (z. B. „Voglio che…“, „Penso che…“, „È possibile che…“)."),
                    .init(label: "Achtung:", text: "io, tu und lui/lei haben exakt dieselbe Form — deshalb wird das Subjekt-Pronomen im Congiuntivo öfter ausgesprochen als sonst im Italienischen üblich, um Verwechslungen zu vermeiden."),
                ])),
                .init(heading: "Endungen", content: .table(columns: ["-are", "-ere", "-ire", "-ire (isc)"], rows: [
                    ["io", "-i", "-a", "-a", "-isca"],
                    ["tu", "-i", "-a", "-a", "-isca"],
                    ["lui/lei", "-i", "-a", "-a", "-isca"],
                    ["noi", "-iamo", "-iamo", "-iamo", "-iamo"],
                    ["voi", "-iate", "-iate", "-iate", "-iate"],
                    ["loro", "-ino", "-ano", "-ano", "-iscano"],
                ])),
                .init(heading: "Verwendung", content: .paragraph("Beispiel: „Penso che lei parli bene italiano“ = „Ich denke, dass sie gut Italienisch spricht“ — im Deutschen bleibt der dass-Satz hier im normalen Indikativ, nur im Italienischen wechselt das Verb in den Congiuntivo.")),
            ]
        ),
        .imperativo: TenseInfo(
            translation: "die Befehlsform — eine ich-Form gibt es dafür nicht",
            sections: [
                .init(heading: "Bildung", content: .list([
                    .init(label: "tu bei -are:", text: "Eigene Form (parla!), anders als im Presente (parli)."),
                    .init(label: "tu bei -ere/-ire:", text: "Einfach die Presente-Form von tu (credi!, dormi!, capisci!)."),
                    .init(label: "Lei (lui/lei) und Loro (formell):", text: "Leihen sich ihre Form komplett vom Congiuntivo presente."),
                    .init(label: "noi und voi:", text: "Entsprechen genau dem Presente indicativo."),
                ])),
                .init(heading: "Verwendung", content: .paragraph("Für direkte Aufforderungen und Befehle: „Parla!“ = „Sprich!“, „Parli!“ = „Sprechen Sie!“ (höflich). Eine Verneinung wird bei tu nicht mit non + Imperativ gebildet, sondern mit non + Infinitiv: „Non parlare!“ = „Sprich nicht!“ — bei allen anderen Formen reicht einfaches non davor.")),
            ]
        ),
    ]
}
