enum VerbCatalog {
    static let seeds: [VerbSeed] = [
        VerbSeed(
            infinitive: "parlare", group: .are, meaning: "sprechen",
            presente: ["parlo", "parli", "parla", "parliamo", "parlate", "parlano"],
            imperfetto: ["parlavo", "parlavi", "parlava", "parlavamo", "parlavate", "parlavano"],
            futuro: ["parlerò", "parlerai", "parlerà", "parleremo", "parlerete", "parleranno"],
            dePresente: ["spreche", "sprichst", "spricht", "sprechen", "sprecht", "sprechen"],
            deImperfetto: ["sprach", "sprachst", "sprach", "sprachen", "spracht", "sprachen"],
            deFuturo: ["werde sprechen", "wirst sprechen", "wird sprechen", "werden sprechen", "werdet sprechen", "werden sprechen"],
            participle: "parlato", auxiliary: .avere,
            deParticiple: "gesprochen", deAuxiliary: .haben,
            deImperative: "sprich"
        ),
        VerbSeed(
            infinitive: "guardare", group: .are, meaning: "schauen",
            presente: ["guardo", "guardi", "guarda", "guardiamo", "guardate", "guardano"],
            imperfetto: ["guardavo", "guardavi", "guardava", "guardavamo", "guardavate", "guardavano"],
            futuro: ["guarderò", "guarderai", "guarderà", "guarderemo", "guarderete", "guarderanno"],
            dePresente: ["schaue", "schaust", "schaut", "schauen", "schaut", "schauen"],
            deImperfetto: ["schaute", "schautest", "schaute", "schauten", "schautet", "schauten"],
            deFuturo: ["werde schauen", "wirst schauen", "wird schauen", "werden schauen", "werdet schauen", "werden schauen"],
            participle: "guardato", auxiliary: .avere,
            deParticiple: "geschaut", deAuxiliary: .haben,
            deImperative: "schau"
        ),
        VerbSeed(
            infinitive: "lavorare", group: .are, meaning: "arbeiten",
            presente: ["lavoro", "lavori", "lavora", "lavoriamo", "lavorate", "lavorano"],
            imperfetto: ["lavoravo", "lavoravi", "lavorava", "lavoravamo", "lavoravate", "lavoravano"],
            futuro: ["lavorerò", "lavorerai", "lavorerà", "lavoreremo", "lavorerete", "lavoreranno"],
            dePresente: ["arbeite", "arbeitest", "arbeitet", "arbeiten", "arbeitet", "arbeiten"],
            deImperfetto: ["arbeitete", "arbeitetest", "arbeitete", "arbeiteten", "arbeitetet", "arbeiteten"],
            deFuturo: ["werde arbeiten", "wirst arbeiten", "wird arbeiten", "werden arbeiten", "werdet arbeiten", "werden arbeiten"],
            participle: "lavorato", auxiliary: .avere,
            deParticiple: "gearbeitet", deAuxiliary: .haben,
            deImperative: "arbeite"
        ),
        VerbSeed(
            infinitive: "abitare", group: .are, meaning: "wohnen",
            presente: ["abito", "abiti", "abita", "abitiamo", "abitate", "abitano"],
            imperfetto: ["abitavo", "abitavi", "abitava", "abitavamo", "abitavate", "abitavano"],
            futuro: ["abiterò", "abiterai", "abiterà", "abiteremo", "abiterete", "abiteranno"],
            dePresente: ["wohne", "wohnst", "wohnt", "wohnen", "wohnt", "wohnen"],
            deImperfetto: ["wohnte", "wohntest", "wohnte", "wohnten", "wohntet", "wohnten"],
            deFuturo: ["werde wohnen", "wirst wohnen", "wird wohnen", "werden wohnen", "werdet wohnen", "werden wohnen"],
            participle: "abitato", auxiliary: .avere,
            deParticiple: "gewohnt", deAuxiliary: .haben,
            deImperative: "wohn"
        ),
        VerbSeed(
            infinitive: "camminare", group: .are, meaning: "laufen",
            presente: ["cammino", "cammini", "cammina", "camminiamo", "camminate", "camminano"],
            imperfetto: ["camminavo", "camminavi", "camminava", "camminavamo", "camminavate", "camminavano"],
            futuro: ["camminerò", "camminerai", "camminerà", "cammineremo", "camminerete", "cammineranno"],
            dePresente: ["laufe", "läufst", "läuft", "laufen", "lauft", "laufen"],
            deImperfetto: ["lief", "liefst", "lief", "liefen", "lieft", "liefen"],
            deFuturo: ["werde laufen", "wirst laufen", "wird laufen", "werden laufen", "werdet laufen", "werden laufen"],
            participle: "camminato", auxiliary: .avere,
            deParticiple: "gelaufen", deAuxiliary: .sein,
            deImperative: "lauf"
        ),
        VerbSeed(
            infinitive: "viaggiare", group: .are, meaning: "reisen",
            presente: ["viaggio", "viaggi", "viaggia", "viaggiamo", "viaggiate", "viaggiano"],
            imperfetto: ["viaggiavo", "viaggiavi", "viaggiava", "viaggiavamo", "viaggiavate", "viaggiavano"],
            futuro: ["viaggerò", "viaggerai", "viaggerà", "viaggeremo", "viaggerete", "viaggeranno"],
            dePresente: ["reise", "reist", "reist", "reisen", "reist", "reisen"],
            deImperfetto: ["reiste", "reistest", "reiste", "reisten", "reistet", "reisten"],
            deFuturo: ["werde reisen", "wirst reisen", "wird reisen", "werden reisen", "werdet reisen", "werden reisen"],
            participle: "viaggiato", auxiliary: .avere,
            deParticiple: "gereist", deAuxiliary: .sein,
            deImperative: "reis"
        ),
        VerbSeed(
            infinitive: "passeggiare", group: .are, meaning: "spazieren gehen",
            presente: ["passeggio", "passeggi", "passeggia", "passeggiamo", "passeggiate", "passeggiano"],
            imperfetto: ["passeggiavo", "passeggiavi", "passeggiava", "passeggiavamo", "passeggiavate", "passeggiavano"],
            futuro: ["passeggerò", "passeggerai", "passeggerà", "passeggeremo", "passeggerete", "passeggeranno"],
            dePresente: ["gehe spazieren", "gehst spazieren", "geht spazieren", "gehen spazieren", "geht spazieren", "gehen spazieren"],
            deImperfetto: ["ging spazieren", "gingst spazieren", "ging spazieren", "gingen spazieren", "gingt spazieren", "gingen spazieren"],
            deFuturo: ["werde spazieren gehen", "wirst spazieren gehen", "wird spazieren gehen", "werden spazieren gehen", "werdet spazieren gehen", "werden spazieren gehen"],
            participle: "passeggiato", auxiliary: .avere,
            deParticiple: "spazieren gegangen", deAuxiliary: .sein,
            deImperative: "geh spazieren"
        ),
        VerbSeed(
            infinitive: "guidare", group: .are, meaning: "fahren",
            presente: ["guido", "guidi", "guida", "guidiamo", "guidate", "guidano"],
            imperfetto: ["guidavo", "guidavi", "guidava", "guidavamo", "guidavate", "guidavano"],
            futuro: ["guiderò", "guiderai", "guiderà", "guideremo", "guiderete", "guideranno"],
            dePresente: ["fahre", "fährst", "fährt", "fahren", "fahrt", "fahren"],
            deImperfetto: ["fuhr", "fuhrst", "fuhr", "fuhren", "fuhrt", "fuhren"],
            deFuturo: ["werde fahren", "wirst fahren", "wird fahren", "werden fahren", "werdet fahren", "werden fahren"],
            participle: "guidato", auxiliary: .avere,
            deParticiple: "gefahren", deAuxiliary: .haben,
            deImperative: "fahr"
        ),
        VerbSeed(
            infinitive: "nuotare", group: .are, meaning: "schwimmen",
            presente: ["nuoto", "nuoti", "nuota", "nuotiamo", "nuotate", "nuotano"],
            imperfetto: ["nuotavo", "nuotavi", "nuotava", "nuotavamo", "nuotavate", "nuotavano"],
            futuro: ["nuoterò", "nuoterai", "nuoterà", "nuoteremo", "nuoterete", "nuoteranno"],
            dePresente: ["schwimme", "schwimmst", "schwimmt", "schwimmen", "schwimmt", "schwimmen"],
            deImperfetto: ["schwamm", "schwammst", "schwamm", "schwammen", "schwammt", "schwammen"],
            deFuturo: ["werde schwimmen", "wirst schwimmen", "wird schwimmen", "werden schwimmen", "werdet schwimmen", "werden schwimmen"],
            participle: "nuotato", auxiliary: .avere,
            deParticiple: "geschwommen", deAuxiliary: .haben,
            deImperative: "schwimm"
        ),
        VerbSeed(
            infinitive: "sciare", group: .are, meaning: "Ski fahren",
            presente: ["scio", "scii", "scia", "sciamo", "sciate", "sciano"],
            imperfetto: ["sciavo", "sciavi", "sciava", "sciavamo", "sciavate", "sciavano"],
            futuro: ["scierò", "scierai", "scierà", "scieremo", "scierete", "scieranno"],
            dePresente: ["fahre Ski", "fährst Ski", "fährt Ski", "fahren Ski", "fahrt Ski", "fahren Ski"],
            deImperfetto: ["fuhr Ski", "fuhrst Ski", "fuhr Ski", "fuhren Ski", "fuhrt Ski", "fuhren Ski"],
            deFuturo: ["werde Ski fahren", "wirst Ski fahren", "wird Ski fahren", "werden Ski fahren", "werdet Ski fahren", "werden Ski fahren"],
            participle: "sciato", auxiliary: .avere,
            deParticiple: "Ski gefahren", deAuxiliary: .sein,
            deImperative: "fahr Ski"
        ),
        VerbSeed(
            infinitive: "ballare", group: .are, meaning: "tanzen",
            presente: ["ballo", "balli", "balla", "balliamo", "ballate", "ballano"],
            imperfetto: ["ballavo", "ballavi", "ballava", "ballavamo", "ballavate", "ballavano"],
            futuro: ["ballerò", "ballerai", "ballerà", "balleremo", "ballerete", "balleranno"],
            dePresente: ["tanze", "tanzt", "tanzt", "tanzen", "tanzt", "tanzen"],
            deImperfetto: ["tanzte", "tanztest", "tanzte", "tanzten", "tanztet", "tanzten"],
            deFuturo: ["werde tanzen", "wirst tanzen", "wird tanzen", "werden tanzen", "werdet tanzen", "werden tanzen"],
            participle: "ballato", auxiliary: .avere,
            deParticiple: "getanzt", deAuxiliary: .haben,
            deImperative: "tanz"
        ),
        VerbSeed(
            infinitive: "arrivare", group: .are, meaning: "ankommen",
            presente: ["arrivo", "arrivi", "arriva", "arriviamo", "arrivate", "arrivano"],
            imperfetto: ["arrivavo", "arrivavi", "arrivava", "arrivavamo", "arrivavate", "arrivavano"],
            futuro: ["arriverò", "arriverai", "arriverà", "arriveremo", "arriverete", "arriveranno"],
            dePresente: ["komme an", "kommst an", "kommt an", "kommen an", "kommt an", "kommen an"],
            deImperfetto: ["kam an", "kamst an", "kam an", "kamen an", "kamt an", "kamen an"],
            deFuturo: ["werde ankommen", "wirst ankommen", "wird ankommen", "werden ankommen", "werdet ankommen", "werden ankommen"],
            participle: "arrivato", auxiliary: .essere,
            deParticiple: "angekommen", deAuxiliary: .sein,
            deImperative: "komm an"
        ),
        VerbSeed(
            infinitive: "diventare", group: .are, meaning: "werden",
            presente: ["divento", "diventi", "diventa", "diventiamo", "diventate", "diventano"],
            imperfetto: ["diventavo", "diventavi", "diventava", "diventavamo", "diventavate", "diventavano"],
            futuro: ["diventerò", "diventerai", "diventerà", "diventeremo", "diventerete", "diventeranno"],
            dePresente: ["werde", "wirst", "wird", "werden", "werdet", "werden"],
            deImperfetto: ["wurde", "wurdest", "wurde", "wurden", "wurdet", "wurden"],
            deFuturo: ["werde werden", "wirst werden", "wird werden", "werden werden", "werdet werden", "werden werden"],
            participle: "diventato", auxiliary: .essere,
            deParticiple: "geworden", deAuxiliary: .sein,
            deImperative: "werde"
        ),
        VerbSeed(
            infinitive: "durare", group: .are, meaning: "dauern",
            presente: ["duro", "duri", "dura", "duriamo", "durate", "durano"],
            imperfetto: ["duravo", "duravi", "durava", "duravamo", "duravate", "duravano"],
            futuro: ["durerò", "durerai", "durerà", "dureremo", "durerete", "dureranno"],
            dePresente: ["dauere", "dauerst", "dauert", "dauern", "dauert", "dauern"],
            deImperfetto: ["dauerte", "dauertest", "dauerte", "dauerten", "dauertet", "dauerten"],
            deFuturo: ["werde dauern", "wirst dauern", "wird dauern", "werden dauern", "werdet dauern", "werden dauern"],
            participle: "durato", auxiliary: .essere,
            deParticiple: "gedauert", deAuxiliary: .haben,
            deImperative: "dauer"
        ),
        VerbSeed(
            infinitive: "entrare", group: .are, meaning: "eintreten",
            presente: ["entro", "entri", "entra", "entriamo", "entrate", "entrano"],
            imperfetto: ["entravo", "entravi", "entrava", "entravamo", "entravate", "entravano"],
            futuro: ["entrerò", "entrerai", "entrerà", "entreremo", "entrerete", "entreranno"],
            dePresente: ["trete ein", "trittst ein", "tritt ein", "treten ein", "tretet ein", "treten ein"],
            deImperfetto: ["trat ein", "tratst ein", "trat ein", "traten ein", "tratet ein", "traten ein"],
            deFuturo: ["werde eintreten", "wirst eintreten", "wird eintreten", "werden eintreten", "werdet eintreten", "werden eintreten"],
            participle: "entrato", auxiliary: .essere,
            deParticiple: "eingetreten", deAuxiliary: .sein,
            deImperative: "tritt ein"
        ),
        VerbSeed(
            infinitive: "mancare", group: .are, meaning: "fehlen",
            presente: ["manco", "manchi", "manca", "manchiamo", "mancate", "mancano"],
            imperfetto: ["mancavo", "mancavi", "mancava", "mancavamo", "mancavate", "mancavano"],
            futuro: ["mancherò", "mancherai", "mancherà", "mancheremo", "mancherete", "mancheranno"],
            dePresente: ["fehle", "fehlst", "fehlt", "fehlen", "fehlt", "fehlen"],
            deImperfetto: ["fehlte", "fehltest", "fehlte", "fehlten", "fehltet", "fehlten"],
            deFuturo: ["werde fehlen", "wirst fehlen", "wird fehlen", "werden fehlen", "werdet fehlen", "werden fehlen"],
            participle: "mancato", auxiliary: .essere,
            deParticiple: "gefehlt", deAuxiliary: .haben,
            deImperative: "fehl"
        ),
        VerbSeed(
            infinitive: "restare", group: .are, meaning: "bleiben",
            presente: ["resto", "resti", "resta", "restiamo", "restate", "restano"],
            imperfetto: ["restavo", "restavi", "restava", "restavamo", "restavate", "restavano"],
            futuro: ["resterò", "resterai", "resterà", "resteremo", "resterete", "resteranno"],
            dePresente: ["bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"],
            deImperfetto: ["blieb", "bliebst", "blieb", "blieben", "bliebt", "blieben"],
            deFuturo: ["werde bleiben", "wirst bleiben", "wird bleiben", "werden bleiben", "werdet bleiben", "werden bleiben"],
            participle: "restato", auxiliary: .essere,
            deParticiple: "geblieben", deAuxiliary: .sein,
            deImperative: "bleib"
        ),
        VerbSeed(
            infinitive: "sembrare", group: .are, meaning: "scheinen",
            presente: ["sembro", "sembri", "sembra", "sembriamo", "sembrate", "sembrano"],
            imperfetto: ["sembravo", "sembravi", "sembrava", "sembravamo", "sembravate", "sembravano"],
            futuro: ["sembrerò", "sembrerai", "sembrerà", "sembreremo", "sembrerete", "sembreranno"],
            dePresente: ["scheine", "scheinst", "scheint", "scheinen", "scheint", "scheinen"],
            deImperfetto: ["schien", "schienst", "schien", "schienen", "schient", "schienen"],
            deFuturo: ["werde scheinen", "wirst scheinen", "wird scheinen", "werden scheinen", "werdet scheinen", "werden scheinen"],
            participle: "sembrato", auxiliary: .essere,
            deParticiple: "geschienen", deAuxiliary: .haben,
            deImperative: "schein"
        ),
        VerbSeed(
            infinitive: "tornare", group: .are, meaning: "zurückkehren",
            presente: ["torno", "torni", "torna", "torniamo", "tornate", "tornano"],
            imperfetto: ["tornavo", "tornavi", "tornava", "tornavamo", "tornavate", "tornavano"],
            futuro: ["tornerò", "tornerai", "tornerà", "torneremo", "tornerete", "torneranno"],
            dePresente: ["kehre zurück", "kehrst zurück", "kehrt zurück", "kehren zurück", "kehrt zurück", "kehren zurück"],
            deImperfetto: ["kehrte zurück", "kehrtest zurück", "kehrte zurück", "kehrten zurück", "kehrtet zurück", "kehrten zurück"],
            deFuturo: ["werde zurückkehren", "wirst zurückkehren", "wird zurückkehren", "werden zurückkehren", "werdet zurückkehren", "werden zurückkehren"],
            participle: "tornato", auxiliary: .essere,
            deParticiple: "zurückgekehrt", deAuxiliary: .sein,
            deImperative: "kehr zurück"
        ),
        VerbSeed(
            infinitive: "bastare", group: .are, meaning: "reichen",
            presente: ["basto", "basti", "basta", "bastiamo", "bastate", "bastano"],
            imperfetto: ["bastavo", "bastavi", "bastava", "bastavamo", "bastavate", "bastavano"],
            futuro: ["basterò", "basterai", "basterà", "basteremo", "basterete", "basteranno"],
            dePresente: ["reiche", "reichst", "reicht", "reichen", "reicht", "reichen"],
            deImperfetto: ["reichte", "reichtest", "reichte", "reichten", "reichtet", "reichten"],
            deFuturo: ["werde reichen", "wirst reichen", "wird reichen", "werden reichen", "werdet reichen", "werden reichen"],
            participle: "bastato", auxiliary: .essere,
            deParticiple: "gereicht", deAuxiliary: .haben,
            deImperative: "reich"
        ),
        VerbSeed(
            infinitive: "credere", group: .ere, meaning: "glauben",
            presente: ["credo", "credi", "crede", "crediamo", "credete", "credono"],
            imperfetto: ["credevo", "credevi", "credeva", "credevamo", "credevate", "credevano"],
            futuro: ["crederò", "crederai", "crederà", "crederemo", "crederete", "crederanno"],
            dePresente: ["glaube", "glaubst", "glaubt", "glauben", "glaubt", "glauben"],
            deImperfetto: ["glaubte", "glaubtest", "glaubte", "glaubten", "glaubtet", "glaubten"],
            deFuturo: ["werde glauben", "wirst glauben", "wird glauben", "werden glauben", "werdet glauben", "werden glauben"],
            participle: "creduto", auxiliary: .avere,
            deParticiple: "geglaubt", deAuxiliary: .haben,
            deImperative: "glaub"
        ),
        VerbSeed(
            infinitive: "vendere", group: .ere, meaning: "verkaufen",
            presente: ["vendo", "vendi", "vende", "vendiamo", "vendete", "vendono"],
            imperfetto: ["vendevo", "vendevi", "vendeva", "vendevamo", "vendevate", "vendevano"],
            futuro: ["venderò", "venderai", "venderà", "venderemo", "venderete", "venderanno"],
            dePresente: ["verkaufe", "verkaufst", "verkauft", "verkaufen", "verkauft", "verkaufen"],
            deImperfetto: ["verkaufte", "verkauftest", "verkaufte", "verkauften", "verkauftet", "verkauften"],
            deFuturo: ["werde verkaufen", "wirst verkaufen", "wird verkaufen", "werden verkaufen", "werdet verkaufen", "werden verkaufen"],
            participle: "venduto", auxiliary: .avere,
            deParticiple: "verkauft", deAuxiliary: .haben,
            deImperative: "verkauf"
        ),
        VerbSeed(
            infinitive: "ricevere", group: .ere, meaning: "bekommen",
            presente: ["ricevo", "ricevi", "riceve", "riceviamo", "ricevete", "ricevono"],
            imperfetto: ["ricevevo", "ricevevi", "riceveva", "ricevevamo", "ricevevate", "ricevevano"],
            futuro: ["riceverò", "riceverai", "riceverà", "riceveremo", "riceverete", "riceveranno"],
            dePresente: ["bekomme", "bekommst", "bekommt", "bekommen", "bekommt", "bekommen"],
            deImperfetto: ["bekam", "bekamst", "bekam", "bekamen", "bekamt", "bekamen"],
            deFuturo: ["werde bekommen", "wirst bekommen", "wird bekommen", "werden bekommen", "werdet bekommen", "werden bekommen"],
            participle: "ricevuto", auxiliary: .avere,
            deParticiple: "bekommen", deAuxiliary: .haben,
            deImperative: "bekomm"
        ),
        VerbSeed(
            infinitive: "temere", group: .ere, meaning: "fürchten",
            presente: ["temo", "temi", "teme", "temiamo", "temete", "temono"],
            imperfetto: ["temevo", "temevi", "temeva", "temevamo", "temevate", "temevano"],
            futuro: ["temerò", "temerai", "temerà", "temeremo", "temerete", "temeranno"],
            dePresente: ["fürchte", "fürchtest", "fürchtet", "fürchten", "fürchtet", "fürchten"],
            deImperfetto: ["fürchtete", "fürchtetest", "fürchtete", "fürchteten", "fürchtetet", "fürchteten"],
            deFuturo: ["werde fürchten", "wirst fürchten", "wird fürchten", "werden fürchten", "werdet fürchten", "werden fürchten"],
            participle: "temuto", auxiliary: .avere,
            deParticiple: "gefürchtet", deAuxiliary: .haben,
            deImperative: "fürchte"
        ),
        VerbSeed(
            infinitive: "ripetere", group: .ere, meaning: "wiederholen",
            presente: ["ripeto", "ripeti", "ripete", "ripetiamo", "ripetete", "ripetono"],
            imperfetto: ["ripetevo", "ripetevi", "ripeteva", "ripetevamo", "ripetevate", "ripetevano"],
            futuro: ["ripeterò", "ripeterai", "ripeterà", "ripeteremo", "ripeterete", "ripeteranno"],
            dePresente: ["wiederhole", "wiederholst", "wiederholt", "wiederholen", "wiederholt", "wiederholen"],
            deImperfetto: ["wiederholte", "wiederholtest", "wiederholte", "wiederholten", "wiederholtet", "wiederholten"],
            deFuturo: ["werde wiederholen", "wirst wiederholen", "wird wiederholen", "werden wiederholen", "werdet wiederholen", "werden wiederholen"],
            participle: "ripetuto", auxiliary: .avere,
            deParticiple: "wiederholt", deAuxiliary: .haben,
            deImperative: "wiederhole"
        ),
        VerbSeed(
            infinitive: "battere", group: .ere, meaning: "schlagen",
            presente: ["batto", "batti", "batte", "battiamo", "battete", "battono"],
            imperfetto: ["battevo", "battevi", "batteva", "battevamo", "battevate", "battevano"],
            futuro: ["batterò", "batterai", "batterà", "batteremo", "batterete", "batteranno"],
            dePresente: ["schlage", "schlägst", "schlägt", "schlagen", "schlagt", "schlagen"],
            deImperfetto: ["schlug", "schlugst", "schlug", "schlugen", "schlugt", "schlugen"],
            deFuturo: ["werde schlagen", "wirst schlagen", "wird schlagen", "werden schlagen", "werdet schlagen", "werden schlagen"],
            participle: "battuto", auxiliary: .avere,
            deParticiple: "geschlagen", deAuxiliary: .haben,
            deImperative: "schlag"
        ),
        VerbSeed(
            infinitive: "cedere", group: .ere, meaning: "nachgeben",
            presente: ["cedo", "cedi", "cede", "cediamo", "cedete", "cedono"],
            imperfetto: ["cedevo", "cedevi", "cedeva", "cedevamo", "cedevate", "cedevano"],
            futuro: ["cederò", "cederai", "cederà", "cederemo", "cederete", "cederanno"],
            dePresente: ["gebe nach", "gibst nach", "gibt nach", "geben nach", "gebt nach", "geben nach"],
            deImperfetto: ["gab nach", "gabst nach", "gab nach", "gaben nach", "gabt nach", "gaben nach"],
            deFuturo: ["werde nachgeben", "wirst nachgeben", "wird nachgeben", "werden nachgeben", "werdet nachgeben", "werden nachgeben"],
            participle: "ceduto", auxiliary: .avere,
            deParticiple: "nachgegeben", deAuxiliary: .haben,
            deImperative: "gib nach"
        ),
        VerbSeed(
            infinitive: "premere", group: .ere, meaning: "drücken",
            presente: ["premo", "premi", "preme", "premiamo", "premete", "premono"],
            imperfetto: ["premevo", "premevi", "premeva", "premevamo", "premevate", "premevano"],
            futuro: ["premerò", "premerai", "premerà", "premeremo", "premerete", "premeranno"],
            dePresente: ["drücke", "drückst", "drückt", "drücken", "drückt", "drücken"],
            deImperfetto: ["drückte", "drücktest", "drückte", "drückten", "drücktet", "drückten"],
            deFuturo: ["werde drücken", "wirst drücken", "wird drücken", "werden drücken", "werdet drücken", "werden drücken"],
            participle: "premuto", auxiliary: .avere,
            deParticiple: "gedrückt", deAuxiliary: .haben,
            deImperative: "drück"
        ),
        VerbSeed(
            infinitive: "correre", group: .ere, meaning: "rennen",
            presente: ["corro", "corri", "corre", "corriamo", "correte", "corrono"],
            imperfetto: ["correvo", "correvi", "correva", "correvamo", "correvate", "correvano"],
            futuro: ["correrò", "correrai", "correrà", "correremo", "correrete", "correranno"],
            dePresente: ["renne", "rennst", "rennt", "rennen", "rennt", "rennen"],
            deImperfetto: ["rannte", "ranntest", "rannte", "rannten", "ranntet", "rannten"],
            deFuturo: ["werde rennen", "wirst rennen", "wird rennen", "werden rennen", "werdet rennen", "werden rennen"],
            participle: "corso", auxiliary: .avere,
            deParticiple: "gerannt", deAuxiliary: .sein,
            deImperative: "renn"
        ),
        VerbSeed(
            infinitive: "scendere", group: .ere, meaning: "hinuntergehen",
            presente: ["scendo", "scendi", "scende", "scendiamo", "scendete", "scendono"],
            imperfetto: ["scendevo", "scendevi", "scendeva", "scendevamo", "scendevate", "scendevano"],
            futuro: ["scenderò", "scenderai", "scenderà", "scenderemo", "scenderete", "scenderanno"],
            dePresente: ["gehe hinunter", "gehst hinunter", "geht hinunter", "gehen hinunter", "geht hinunter", "gehen hinunter"],
            deImperfetto: ["ging hinunter", "gingst hinunter", "ging hinunter", "gingen hinunter", "gingt hinunter", "gingen hinunter"],
            deFuturo: ["werde hinuntergehen", "wirst hinuntergehen", "wird hinuntergehen", "werden hinuntergehen", "werdet hinuntergehen", "werden hinuntergehen"],
            participle: "sceso", auxiliary: .essere,
            deParticiple: "hinuntergegangen", deAuxiliary: .sein,
            deImperative: "geh hinunter"
        ),
        VerbSeed(
            infinitive: "perdere", group: .ere, meaning: "verlieren",
            presente: ["perdo", "perdi", "perde", "perdiamo", "perdete", "perdono"],
            imperfetto: ["perdevo", "perdevi", "perdeva", "perdevamo", "perdevate", "perdevano"],
            futuro: ["perderò", "perderai", "perderà", "perderemo", "perderete", "perderanno"],
            dePresente: ["verliere", "verlierst", "verliert", "verlieren", "verliert", "verlieren"],
            deImperfetto: ["verlor", "verlorst", "verlor", "verloren", "verlort", "verloren"],
            deFuturo: ["werde verlieren", "wirst verlieren", "wird verlieren", "werden verlieren", "werdet verlieren", "werden verlieren"],
            participle: "perso", auxiliary: .avere,
            deParticiple: "verloren", deAuxiliary: .haben,
            deImperative: "verlier"
        ),
        VerbSeed(
            infinitive: "vincere", group: .ere, meaning: "gewinnen",
            presente: ["vinco", "vinci", "vince", "vinciamo", "vincete", "vincono"],
            imperfetto: ["vincevo", "vincevi", "vinceva", "vincevamo", "vincevate", "vincevano"],
            futuro: ["vincerò", "vincerai", "vincerà", "vinceremo", "vincerete", "vinceranno"],
            dePresente: ["gewinne", "gewinnst", "gewinnt", "gewinnen", "gewinnt", "gewinnen"],
            deImperfetto: ["gewann", "gewannst", "gewann", "gewannen", "gewannt", "gewannen"],
            deFuturo: ["werde gewinnen", "wirst gewinnen", "wird gewinnen", "werden gewinnen", "werdet gewinnen", "werden gewinnen"],
            participle: "vinto", auxiliary: .avere,
            deParticiple: "gewonnen", deAuxiliary: .haben,
            deImperative: "gewinn"
        ),
        VerbSeed(
            infinitive: "dormire", group: .ire, meaning: "schlafen",
            presente: ["dormo", "dormi", "dorme", "dormiamo", "dormite", "dormono"],
            imperfetto: ["dormivo", "dormivi", "dormiva", "dormivamo", "dormivate", "dormivano"],
            futuro: ["dormirò", "dormirai", "dormirà", "dormiremo", "dormirete", "dormiranno"],
            dePresente: ["schlafe", "schläfst", "schläft", "schlafen", "schlaft", "schlafen"],
            deImperfetto: ["schlief", "schliefst", "schlief", "schliefen", "schlieft", "schliefen"],
            deFuturo: ["werde schlafen", "wirst schlafen", "wird schlafen", "werden schlafen", "werdet schlafen", "werden schlafen"],
            participle: "dormito", auxiliary: .avere,
            deParticiple: "geschlafen", deAuxiliary: .haben,
            deImperative: "schlaf"
        ),
        VerbSeed(
            infinitive: "seguire", group: .ire, meaning: "folgen",
            presente: ["seguo", "segui", "segue", "seguiamo", "seguite", "seguono"],
            imperfetto: ["seguivo", "seguivi", "seguiva", "seguivamo", "seguivate", "seguivano"],
            futuro: ["seguirò", "seguirai", "seguirà", "seguiremo", "seguirete", "seguiranno"],
            dePresente: ["folge", "folgst", "folgt", "folgen", "folgt", "folgen"],
            deImperfetto: ["folgte", "folgtest", "folgte", "folgten", "folgtet", "folgten"],
            deFuturo: ["werde folgen", "wirst folgen", "wird folgen", "werden folgen", "werdet folgen", "werden folgen"],
            participle: "seguito", auxiliary: .avere,
            deParticiple: "gefolgt", deAuxiliary: .sein,
            deImperative: "folge"
        ),
        VerbSeed(
            infinitive: "sentire", group: .ire, meaning: "fühlen",
            presente: ["sento", "senti", "sente", "sentiamo", "sentite", "sentono"],
            imperfetto: ["sentivo", "sentivi", "sentiva", "sentivamo", "sentivate", "sentivano"],
            futuro: ["sentirò", "sentirai", "sentirà", "sentiremo", "sentirete", "sentiranno"],
            dePresente: ["fühle", "fühlst", "fühlt", "fühlen", "fühlt", "fühlen"],
            deImperfetto: ["fühlte", "fühltest", "fühlte", "fühlten", "fühltet", "fühlten"],
            deFuturo: ["werde fühlen", "wirst fühlen", "wird fühlen", "werden fühlen", "werdet fühlen", "werden fühlen"],
            participle: "sentito", auxiliary: .avere,
            deParticiple: "gefühlt", deAuxiliary: .haben,
            deImperative: "fühl"
        ),
        VerbSeed(
            infinitive: "partire", group: .ire, meaning: "abreisen",
            presente: ["parto", "parti", "parte", "partiamo", "partite", "partono"],
            imperfetto: ["partivo", "partivi", "partiva", "partivamo", "partivate", "partivano"],
            futuro: ["partirò", "partirai", "partirà", "partiremo", "partirete", "partiranno"],
            dePresente: ["reise ab", "reist ab", "reist ab", "reisen ab", "reist ab", "reisen ab"],
            deImperfetto: ["reiste ab", "reistest ab", "reiste ab", "reisten ab", "reistet ab", "reisten ab"],
            deFuturo: ["werde abreisen", "wirst abreisen", "wird abreisen", "werden abreisen", "werdet abreisen", "werden abreisen"],
            participle: "partito", auxiliary: .essere,
            deParticiple: "abgereist", deAuxiliary: .sein,
            deImperative: "reise ab"
        ),
        VerbSeed(
            infinitive: "servire", group: .ire, meaning: "dienen",
            presente: ["servo", "servi", "serve", "serviamo", "servite", "servono"],
            imperfetto: ["servivo", "servivi", "serviva", "servivamo", "servivate", "servivano"],
            futuro: ["servirò", "servirai", "servirà", "serviremo", "servirete", "serviranno"],
            dePresente: ["diene", "dienst", "dient", "dienen", "dient", "dienen"],
            deImperfetto: ["diente", "dientest", "diente", "dienten", "dientet", "dienten"],
            deFuturo: ["werde dienen", "wirst dienen", "wird dienen", "werden dienen", "werdet dienen", "werden dienen"],
            participle: "servito", auxiliary: .avere,
            deParticiple: "gedient", deAuxiliary: .haben,
            deImperative: "dien"
        ),
        VerbSeed(
            infinitive: "vestire", group: .ire, meaning: "anziehen",
            presente: ["vesto", "vesti", "veste", "vestiamo", "vestite", "vestono"],
            imperfetto: ["vestivo", "vestivi", "vestiva", "vestivamo", "vestivate", "vestivano"],
            futuro: ["vestirò", "vestirai", "vestirà", "vestiremo", "vestirete", "vestiranno"],
            dePresente: ["ziehe an", "ziehst an", "zieht an", "ziehen an", "zieht an", "ziehen an"],
            deImperfetto: ["zog an", "zogst an", "zog an", "zogen an", "zogt an", "zogen an"],
            deFuturo: ["werde anziehen", "wirst anziehen", "wird anziehen", "werden anziehen", "werdet anziehen", "werden anziehen"],
            participle: "vestito", auxiliary: .avere,
            deParticiple: "angezogen", deAuxiliary: .haben,
            deImperative: "zieh an"
        ),
        VerbSeed(
            infinitive: "fuggire", group: .ire, meaning: "fliehen",
            presente: ["fuggo", "fuggi", "fugge", "fuggiamo", "fuggite", "fuggono"],
            imperfetto: ["fuggivo", "fuggivi", "fuggiva", "fuggivamo", "fuggivate", "fuggivano"],
            futuro: ["fuggirò", "fuggirai", "fuggirà", "fuggiremo", "fuggirete", "fuggiranno"],
            dePresente: ["fliehe", "fliehst", "flieht", "fliehen", "flieht", "fliehen"],
            deImperfetto: ["floh", "flohst", "floh", "flohen", "floht", "flohen"],
            deFuturo: ["werde fliehen", "wirst fliehen", "wird fliehen", "werden fliehen", "werdet fliehen", "werden fliehen"],
            participle: "fuggito", auxiliary: .essere,
            deParticiple: "geflohen", deAuxiliary: .sein,
            deImperative: "flieh"
        ),
        VerbSeed(
            infinitive: "bollire", group: .ire, meaning: "kochen",
            presente: ["bollo", "bolli", "bolle", "bolliamo", "bollite", "bollono"],
            imperfetto: ["bollivo", "bollivi", "bolliva", "bollivamo", "bollivate", "bollivano"],
            futuro: ["bollirò", "bollirai", "bollirà", "bolliremo", "bollirete", "bolliranno"],
            dePresente: ["koche", "kochst", "kocht", "kochen", "kocht", "kochen"],
            deImperfetto: ["kochte", "kochtest", "kochte", "kochten", "kochtet", "kochten"],
            deFuturo: ["werde kochen", "wirst kochen", "wird kochen", "werden kochen", "werdet kochen", "werden kochen"],
            participle: "bollito", auxiliary: .avere,
            deParticiple: "gekocht", deAuxiliary: .haben,
            deImperative: "koch"
        ),
        VerbSeed(
            infinitive: "mentire", group: .ire, meaning: "lügen",
            presente: ["mento", "menti", "mente", "mentiamo", "mentite", "mentono"],
            imperfetto: ["mentivo", "mentivi", "mentiva", "mentivamo", "mentivate", "mentivano"],
            futuro: ["mentirò", "mentirai", "mentirà", "mentiremo", "mentirete", "mentiranno"],
            dePresente: ["lüge", "lügst", "lügt", "lügen", "lügt", "lügen"],
            deImperfetto: ["log", "logst", "log", "logen", "logt", "logen"],
            deFuturo: ["werde lügen", "wirst lügen", "wird lügen", "werden lügen", "werdet lügen", "werden lügen"],
            participle: "mentito", auxiliary: .avere,
            deParticiple: "gelogen", deAuxiliary: .haben,
            deImperative: "lüg"
        ),
        VerbSeed(
            infinitive: "offrire", group: .ire, meaning: "anbieten",
            presente: ["offro", "offri", "offre", "offriamo", "offrite", "offrono"],
            imperfetto: ["offrivo", "offrivi", "offriva", "offrivamo", "offrivate", "offrivano"],
            futuro: ["offrirò", "offrirai", "offrirà", "offriremo", "offrirete", "offriranno"],
            dePresente: ["biete an", "bietest an", "bietet an", "bieten an", "bietet an", "bieten an"],
            deImperfetto: ["bot an", "botst an", "bot an", "boten an", "botet an", "boten an"],
            deFuturo: ["werde anbieten", "wirst anbieten", "wird anbieten", "werden anbieten", "werdet anbieten", "werden anbieten"],
            participle: "offerto", auxiliary: .avere,
            deParticiple: "angeboten", deAuxiliary: .haben,
            deImperative: "biete an"
        ),
        VerbSeed(
            infinitive: "soffrire", group: .ire, meaning: "leiden",
            presente: ["soffro", "soffri", "soffre", "soffriamo", "soffrite", "soffrono"],
            imperfetto: ["soffrivo", "soffrivi", "soffriva", "soffrivamo", "soffrivate", "soffrivano"],
            futuro: ["soffrirò", "soffrirai", "soffrirà", "soffriremo", "soffrirete", "soffriranno"],
            dePresente: ["leide", "leidest", "leidet", "leiden", "leidet", "leiden"],
            deImperfetto: ["litt", "littst", "litt", "litten", "littet", "litten"],
            deFuturo: ["werde leiden", "wirst leiden", "wird leiden", "werden leiden", "werdet leiden", "werden leiden"],
            participle: "sofferto", auxiliary: .avere,
            deParticiple: "gelitten", deAuxiliary: .haben,
            deImperative: "leide"
        ),
        VerbSeed(
            infinitive: "scoprire", group: .ire, meaning: "entdecken",
            presente: ["scopro", "scopri", "scopre", "scopriamo", "scoprite", "scoprono"],
            imperfetto: ["scoprivo", "scoprivi", "scopriva", "scoprivamo", "scoprivate", "scoprivano"],
            futuro: ["scoprirò", "scoprirai", "scoprirà", "scopriremo", "scoprirete", "scopriranno"],
            dePresente: ["entdecke", "entdeckst", "entdeckt", "entdecken", "entdeckt", "entdecken"],
            deImperfetto: ["entdeckte", "entdecktest", "entdeckte", "entdeckten", "entdecktet", "entdeckten"],
            deFuturo: ["werde entdecken", "wirst entdecken", "wird entdecken", "werden entdecken", "werdet entdecken", "werden entdecken"],
            participle: "scoperto", auxiliary: .avere,
            deParticiple: "entdeckt", deAuxiliary: .haben,
            deImperative: "entdeck"
        ),
        VerbSeed(
            infinitive: "capire", group: .ireIsc, meaning: "verstehen",
            presente: ["capisco", "capisci", "capisce", "capiamo", "capite", "capiscono"],
            imperfetto: ["capivo", "capivi", "capiva", "capivamo", "capivate", "capivano"],
            futuro: ["capirò", "capirai", "capirà", "capiremo", "capirete", "capiranno"],
            dePresente: ["verstehe", "verstehst", "versteht", "verstehen", "versteht", "verstehen"],
            deImperfetto: ["verstand", "verstandest", "verstand", "verstanden", "verstandet", "verstanden"],
            deFuturo: ["werde verstehen", "wirst verstehen", "wird verstehen", "werden verstehen", "werdet verstehen", "werden verstehen"],
            participle: "capito", auxiliary: .avere,
            deParticiple: "verstanden", deAuxiliary: .haben,
            deImperative: "versteh"
        ),
        VerbSeed(
            infinitive: "finire", group: .ireIsc, meaning: "beenden",
            presente: ["finisco", "finisci", "finisce", "finiamo", "finite", "finiscono"],
            imperfetto: ["finivo", "finivi", "finiva", "finivamo", "finivate", "finivano"],
            futuro: ["finirò", "finirai", "finirà", "finiremo", "finirete", "finiranno"],
            dePresente: ["beende", "beendest", "beendet", "beenden", "beendet", "beenden"],
            deImperfetto: ["beendete", "beendetest", "beendete", "beendeten", "beendetet", "beendeten"],
            deFuturo: ["werde beenden", "wirst beenden", "wird beenden", "werden beenden", "werdet beenden", "werden beenden"],
            participle: "finito", auxiliary: .avere,
            deParticiple: "beendet", deAuxiliary: .haben,
            deImperative: "beende"
        ),
        VerbSeed(
            infinitive: "preferire", group: .ireIsc, meaning: "bevorzugen",
            presente: ["preferisco", "preferisci", "preferisce", "preferiamo", "preferite", "preferiscono"],
            imperfetto: ["preferivo", "preferivi", "preferiva", "preferivamo", "preferivate", "preferivano"],
            futuro: ["preferirò", "preferirai", "preferirà", "preferiremo", "preferirete", "preferiranno"],
            dePresente: ["bevorzuge", "bevorzugst", "bevorzugt", "bevorzugen", "bevorzugt", "bevorzugen"],
            deImperfetto: ["bevorzugte", "bevorzugtest", "bevorzugte", "bevorzugten", "bevorzugtet", "bevorzugten"],
            deFuturo: ["werde bevorzugen", "wirst bevorzugen", "wird bevorzugen", "werden bevorzugen", "werdet bevorzugen", "werden bevorzugen"],
            participle: "preferito", auxiliary: .avere,
            deParticiple: "bevorzugt", deAuxiliary: .haben,
            deImperative: "bevorzuge"
        ),
        VerbSeed(
            infinitive: "pulire", group: .ireIsc, meaning: "putzen",
            presente: ["pulisco", "pulisci", "pulisce", "puliamo", "pulite", "puliscono"],
            imperfetto: ["pulivo", "pulivi", "puliva", "pulivamo", "pulivate", "pulivano"],
            futuro: ["pulirò", "pulirai", "pulirà", "puliremo", "pulirete", "puliranno"],
            dePresente: ["putze", "putzt", "putzt", "putzen", "putzt", "putzen"],
            deImperfetto: ["putzte", "putztest", "putzte", "putzten", "putztet", "putzten"],
            deFuturo: ["werde putzen", "wirst putzen", "wird putzen", "werden putzen", "werdet putzen", "werden putzen"],
            participle: "pulito", auxiliary: .avere,
            deParticiple: "geputzt", deAuxiliary: .haben,
            deImperative: "putz"
        ),
        VerbSeed(
            infinitive: "spedire", group: .ireIsc, meaning: "schicken",
            presente: ["spedisco", "spedisci", "spedisce", "spediamo", "spedite", "spediscono"],
            imperfetto: ["spedivo", "spedivi", "spediva", "spedivamo", "spedivate", "spedivano"],
            futuro: ["spedirò", "spedirai", "spedirà", "spediremo", "spedirete", "spediranno"],
            dePresente: ["schicke", "schickst", "schickt", "schicken", "schickt", "schicken"],
            deImperfetto: ["schickte", "schicktest", "schickte", "schickten", "schicktet", "schickten"],
            deFuturo: ["werde schicken", "wirst schicken", "wird schicken", "werden schicken", "werdet schicken", "werden schicken"],
            participle: "spedito", auxiliary: .avere,
            deParticiple: "geschickt", deAuxiliary: .haben,
            deImperative: "schick"
        ),
        VerbSeed(
            infinitive: "costruire", group: .ireIsc, meaning: "bauen",
            presente: ["costruisco", "costruisci", "costruisce", "costruiamo", "costruite", "costruiscono"],
            imperfetto: ["costruivo", "costruivi", "costruiva", "costruivamo", "costruivate", "costruivano"],
            futuro: ["costruirò", "costruirai", "costruirà", "costruiremo", "costruirete", "costruiranno"],
            dePresente: ["baue", "baust", "baut", "bauen", "baut", "bauen"],
            deImperfetto: ["baute", "bautest", "baute", "bauten", "bautet", "bauten"],
            deFuturo: ["werde bauen", "wirst bauen", "wird bauen", "werden bauen", "werdet bauen", "werden bauen"],
            participle: "costruito", auxiliary: .avere,
            deParticiple: "gebaut", deAuxiliary: .haben,
            deImperative: "bau"
        ),
        VerbSeed(
            infinitive: "obbedire", group: .ireIsc, meaning: "gehorchen",
            presente: ["obbedisco", "obbedisci", "obbedisce", "obbediamo", "obbedite", "obbediscono"],
            imperfetto: ["obbedivo", "obbedivi", "obbediva", "obbedivamo", "obbedivate", "obbedivano"],
            futuro: ["obbedirò", "obbedirai", "obbedirà", "obbediremo", "obbedirete", "obbediranno"],
            dePresente: ["gehorche", "gehorchst", "gehorcht", "gehorchen", "gehorcht", "gehorchen"],
            deImperfetto: ["gehorchte", "gehorchtest", "gehorchte", "gehorchten", "gehorchtet", "gehorchten"],
            deFuturo: ["werde gehorchen", "wirst gehorchen", "wird gehorchen", "werden gehorchen", "werdet gehorchen", "werden gehorchen"],
            participle: "obbedito", auxiliary: .avere,
            deParticiple: "gehorcht", deAuxiliary: .haben,
            deImperative: "gehorch"
        ),
        VerbSeed(
            infinitive: "guarire", group: .ireIsc, meaning: "heilen",
            presente: ["guarisco", "guarisci", "guarisce", "guariamo", "guarite", "guariscono"],
            imperfetto: ["guarivo", "guarivi", "guariva", "guarivamo", "guarivate", "guarivano"],
            futuro: ["guarirò", "guarirai", "guarirà", "guariremo", "guarirete", "guariranno"],
            dePresente: ["heile", "heilst", "heilt", "heilen", "heilt", "heilen"],
            deImperfetto: ["heilte", "heiltest", "heilte", "heilten", "heiltet", "heilten"],
            deFuturo: ["werde heilen", "wirst heilen", "wird heilen", "werden heilen", "werdet heilen", "werden heilen"],
            participle: "guarito", auxiliary: .avere,
            deParticiple: "geheilt", deAuxiliary: .haben,
            deImperative: "heile"
        ),
        VerbSeed(
            infinitive: "suggerire", group: .ireIsc, meaning: "vorschlagen",
            presente: ["suggerisco", "suggerisci", "suggerisce", "suggeriamo", "suggerite", "suggeriscono"],
            imperfetto: ["suggerivo", "suggerivi", "suggeriva", "suggerivamo", "suggerivate", "suggerivano"],
            futuro: ["suggerirò", "suggerirai", "suggerirà", "suggeriremo", "suggerirete", "suggeriranno"],
            dePresente: ["schlage vor", "schlägst vor", "schlägt vor", "schlagen vor", "schlagt vor", "schlagen vor"],
            deImperfetto: ["schlug vor", "schlugst vor", "schlug vor", "schlugen vor", "schlugt vor", "schlugen vor"],
            deFuturo: ["werde vorschlagen", "wirst vorschlagen", "wird vorschlagen", "werden vorschlagen", "werdet vorschlagen", "werden vorschlagen"],
            participle: "suggerito", auxiliary: .avere,
            deParticiple: "vorgeschlagen", deAuxiliary: .haben,
            deImperative: "schlag vor"
        ),
        VerbSeed(
            infinitive: "reagire", group: .ireIsc, meaning: "reagieren",
            presente: ["reagisco", "reagisci", "reagisce", "reagiamo", "reagite", "reagiscono"],
            imperfetto: ["reagivo", "reagivi", "reagiva", "reagivamo", "reagivate", "reagivano"],
            futuro: ["reagirò", "reagirai", "reagirà", "reagiremo", "reagirete", "reagiranno"],
            dePresente: ["reagiere", "reagierst", "reagiert", "reagieren", "reagiert", "reagieren"],
            deImperfetto: ["reagierte", "reagiertest", "reagierte", "reagierten", "reagiertet", "reagierten"],
            deFuturo: ["werde reagieren", "wirst reagieren", "wird reagieren", "werden reagieren", "werdet reagieren", "werden reagieren"],
            participle: "reagito", auxiliary: .avere,
            deParticiple: "reagiert", deAuxiliary: .haben,
            deImperative: "reagiere"
        ),
        VerbSeed(
            infinitive: "unire", group: .ireIsc, meaning: "vereinen",
            presente: ["unisco", "unisci", "unisce", "uniamo", "unite", "uniscono"],
            imperfetto: ["univo", "univi", "univa", "univamo", "univate", "univano"],
            futuro: ["unirò", "unirai", "unirà", "uniremo", "unirete", "uniranno"],
            dePresente: ["vereine", "vereinst", "vereint", "vereinen", "vereint", "vereinen"],
            deImperfetto: ["vereinte", "vereintest", "vereinte", "vereinten", "vereintet", "vereinten"],
            deFuturo: ["werde vereinen", "wirst vereinen", "wird vereinen", "werden vereinen", "werdet vereinen", "werden vereinen"],
            participle: "unito", auxiliary: .avere,
            deParticiple: "vereint", deAuxiliary: .haben,
            deImperative: "vereine"
        ),
        VerbSeed(
            infinitive: "restituire", group: .ireIsc, meaning: "zurückgeben",
            presente: ["restituisco", "restituisci", "restituisce", "restituiamo", "restituite", "restituiscono"],
            imperfetto: ["restituivo", "restituivi", "restituiva", "restituivamo", "restituivate", "restituivano"],
            futuro: ["restituirò", "restituirai", "restituirà", "restituiremo", "restituirete", "restituiranno"],
            dePresente: ["gebe zurück", "gibst zurück", "gibt zurück", "geben zurück", "gebt zurück", "geben zurück"],
            deImperfetto: ["gab zurück", "gabst zurück", "gab zurück", "gaben zurück", "gabt zurück", "gaben zurück"],
            deFuturo: ["werde zurückgeben", "wirst zurückgeben", "wird zurückgeben", "werden zurückgeben", "werdet zurückgeben", "werden zurückgeben"],
            participle: "restituito", auxiliary: .avere,
            deParticiple: "zurückgegeben", deAuxiliary: .haben,
            deImperative: "gib zurück"
        ),
    ]

    static let groups: [VerbGroupSection] = [
        VerbGroupSection(label: "-are · mit avere im Passato prossimo", verbs: ["parlare", "guardare", "lavorare", "abitare", "camminare", "viaggiare", "passeggiare", "guidare", "nuotare", "sciare", "ballare"]),
        VerbGroupSection(label: "-are · mit essere im Passato prossimo", verbs: ["arrivare", "diventare", "durare", "entrare", "mancare", "restare", "sembrare", "tornare", "bastare"]),
        VerbGroupSection(label: "-ere", verbs: ["credere", "vendere", "ricevere", "temere", "ripetere", "battere", "cedere", "premere", "correre", "scendere", "perdere", "vincere"]),
        VerbGroupSection(label: "-ire · regelmäßig", verbs: ["dormire", "seguire", "sentire", "partire", "servire", "vestire", "fuggire", "bollire", "mentire", "offrire", "soffrire", "scoprire"]),
        VerbGroupSection(label: "-ire · mit -isc-", verbs: ["capire", "finire", "preferire", "pulire", "spedire", "costruire", "obbedire", "guarire", "suggerire", "reagire", "unire", "restituire"]),
    ]
}
