#!/usr/bin/env python3
"""Generates Swift data files and the test fixture from prototype/index.html.

Usage: python3 tools/generate-swift-data.py
Rewrites Italiano/Model/VerbCatalog.swift, Italiano/Model/TenseInfo+Content.swift
and ItalianoTests/prototype-forms.json.
"""
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads(subprocess.check_output(["node", str(ROOT / "tools/extract-prototype.mjs")]))

GROUP_CASE = {"-are": ".are", "-ere": ".ere", "-ire": ".ire", "-ire (isc)": ".ireIsc"}


def s(value):
    return json.dumps(value, ensure_ascii=False)


def arr(values):
    return "[" + ", ".join(s(v) for v in values) + "]"


HEADER = "// Generated by tools/generate-swift-data.py from prototype/index.html.\n// Edit the prototype and re-run the script rather than editing by hand.\n\n"

# ---------- verbs ----------
lines = [HEADER + "enum VerbCatalog {", "    static let seeds: [VerbSeed] = ["]
ordered = [v for g in data["VERB_GROUPS"] for v in g["verbs"]]
for key in ordered:
    v = data["VERBS"][key]
    p = data["PARTICIPLES"][key]
    lines += [
        "        VerbSeed(",
        f"            infinitive: {s(key)}, group: {GROUP_CASE[v['group']]}, meaning: {s(v['meaning'])},",
        f"            presente: {arr(v['presente'])},",
        f"            imperfetto: {arr(v['imperfetto'])},",
        f"            futuro: {arr(v['futuro'])},",
        f"            dePresente: {arr(v['de']['presente'])},",
        f"            deImperfetto: {arr(v['de']['imperfetto'])},",
        f"            deFuturo: {arr(v['de']['futuro'])},",
        f"            participle: {s(p['part'])}, auxiliary: .{p['aux']},",
        f"            deParticiple: {s(p['dePart'])}, deAuxiliary: .{p['deAux']},",
        f"            deImperative: {s(data['DU_IMPERATIV'][key])}",
        "        ),",
    ]
lines += ["    ]", "", "    static let groups: [VerbGroupSection] = ["]
for g in data["VERB_GROUPS"]:
    lines.append(f"        VerbGroupSection(label: {s(g['label'])}, verbs: {arr(g['verbs'])}),")
lines += ["    ]", "}", ""]
(ROOT / "Italiano/Model/VerbCatalog.swift").write_text("\n".join(lines))

# ---------- tense explanations ----------
lines = [HEADER + "extension TenseInfo {", "    static let all: [Tense: TenseInfo] = ["]
for tense, info in data["TENSE_INFO"].items():
    lines.append(f"        .{tense}: TenseInfo(")
    lines.append(f"            translation: {s(info['translation'])},")
    lines.append("            sections: [")
    for sec in info["sections"]:
        if "p" in sec:
            lines.append(f"                .init(heading: {s(sec['h'])}, content: .paragraph({s(sec['p'])})),")
        elif "list" in sec:
            lines.append(f"                .init(heading: {s(sec['h'])}, content: .list([")
            for label, text in sec["list"]:
                lines.append(f"                    .init(label: {s(label)}, text: {s(text)}),")
            lines.append("                ])),")
        else:
            lines.append(f"                .init(heading: {s(sec['h'])}, content: .table(columns: {arr(sec['table'])}, rows: [")
            for row in sec["rows"]:
                lines.append(f"                    {arr(row)},")
            lines.append("                ])),")
    lines += ["            ]", "        ),"]
lines += ["    ]", "}", ""]
(ROOT / "Italiano/Model/TenseInfo+Content.swift").write_text("\n".join(lines))

# ---------- expected forms for the unit tests ----------
tenses = list(data["TENSE_LABELS"].keys())
fixture = {
    key: {
        "it": {t: v[t] for t in tenses},
        "de": {t: v["de"][t] for t in tenses},
    }
    for key, v in data["VERBS"].items()
}
(ROOT / "ItalianoTests/prototype-forms.json").write_text(json.dumps(fixture, ensure_ascii=False, indent=1) + "\n")
print(f"{len(ordered)} verbs, {len(data['TENSE_INFO'])} tense explanations written")
